// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOZEFCjwPXnf9E0es6SQJoam9AbOmFWEo',
    appId: '1:385497139018:web:66fef0e34d2879a8d3e3b3',
    messagingSenderId: '385497139018',
    projectId: 'sip-smea',
    authDomain: 'sip-smea.firebaseapp.com',
    storageBucket: 'sip-smea.firebasestorage.app',
    measurementId: 'G-18EG479QEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTec0zsCbCAiqo4UYNxkGuzqv_03ZmgmM',
    appId: '1:385497139018:android:ccf0bb337e9d0fddd3e3b3',
    messagingSenderId: '385497139018',
    projectId: 'sip-smea',
    storageBucket: 'sip-smea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEobyk_xSYIdcyRPNmb7gsgR36Msi9ddM',
    appId: '1:385497139018:ios:35cfed17f8e9c55ad3e3b3',
    messagingSenderId: '385497139018',
    projectId: 'sip-smea',
    storageBucket: 'sip-smea.firebasestorage.app',
    iosBundleId: 'com.epkl.ePkl',
  );
}
