-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. PROFILES TABLE
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  nisn text unique,
  full_name text,
  class_name text,
  avatar_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 2. COMPANIES TABLE (DUDI)
create table public.companies (
  id bigint generated by default as identity primary key,
  name text not null,
  latitude double precision not null,
  longitude double precision not null,
  radius_meter int default 100,
  address text,
  created_at timestamptz default now()
);

-- 3. PLACEMENTS TABLE (Pivot)
create table public.placements (
  id bigint generated by default as identity primary key,
  student_id uuid references public.profiles(id) not null,
  company_id bigint references public.companies(id) not null,
  start_date date,
  end_date date,
  created_at timestamptz default now()
);

-- 4. ATTENDANCE LOGS TABLE
create table public.attendance_logs (
  id bigint generated by default as identity primary key,
  student_id uuid references public.profiles(id) not null,
  placement_id bigint references public.placements(id),
  check_in_time timestamptz default now(),
  check_out_time timestamptz,
  check_in_lat double precision,
  check_in_long double precision,
  photo_url text,
  status text check (status in ('Hadir', 'Telat', 'Izin', 'Alpha')),
  created_at timestamptz default now()
);

-- 5. DAILY JOURNALS TABLE
create table public.daily_journals (
  id bigint generated by default as identity primary key,
  student_id uuid references public.profiles(id) not null,
  placement_id bigint references public.placements(id),
  activity_title text,
  description text,
  evidence_photo text,
  is_approved boolean default false,
  created_at timestamptz default now()
);

-- ROW LEVEL SECURITY (RLS)
alter table public.profiles enable row level security;
alter table public.companies enable row level security;
alter table public.placements enable row level security;
alter table public.attendance_logs enable row level security;
alter table public.daily_journals enable row level security;

-- Policies

-- Profiles: Anyone can view (for admin/teacher), Users can update own
create policy "Public profiles are viewable by everyone" on public.profiles
  for select using (true);

create policy "Users can update own profile" on public.profiles
  for update using (auth.uid() = id);

create policy "Users can insert own profile" on public.profiles
  for insert with check (auth.uid() = id);

-- Companies: Viewable by everyone (students need to know location)
create policy "Companies are viewable by everyone" on public.companies
  for select using (true);
  
-- Placements: Viewable by everyone
create policy "Placements are viewable by everyone" on public.placements
  for select using (true);

-- Attendance: Users can insert own, view own. Admin can view all (handled via app logic/admin role later, for now public read for simplicity in prototype or restrictive)
-- Secure approach:
create policy "Users can insert own attendance" on public.attendance_logs
  for insert with check (auth.uid() = student_id);

create policy "Users can view own attendance" on public.attendance_logs
  for select using (auth.uid() = student_id);
  
-- Journals: Users can insert own, view own.
create policy "Users can insert own journal" on public.daily_journals
  for insert with check (auth.uid() = student_id);

create policy "Users can view own journal" on public.daily_journals
  for select using (auth.uid() = student_id);
  
-- STORAGE BUCKETS
-- You need to create buckets 'attendances' and 'journal_evidence' in the dashboard manually or via API.
-- This SQL script sets up tables. Buckets are separate.
