-- ============================================================
-- E-PKL Database Setup — Step 2: Tables
-- ============================================================
-- Creates all application tables with correct column types,
-- constraints, and defaults. Run after 01_extensions.sql.
--
-- Tables:
--   1. profiles          — Users (students, teachers, admins)
--   2. companies         — DUDI / PKL placement companies
--   3. placements        — Student ↔ Company assignments
--   4. attendance_logs   — Daily check-in / check-out records
--   5. daily_journals    — Student daily activity journals
--   6. supervisor_assignments — Teacher ↔ Company assignments
--   7. announcements     — School announcements
--   8. notifications     — In-app notification system
--   9. app_config        — Key-value application settings
--  10. audit_logs        — Admin action audit trail
-- ============================================================

-- ────────────────────────────────────────────────────────────
-- 1. PROFILES
-- ────────────────────────────────────────────────────────────
-- This table is created by the Supabase trigger `handle_new_user`
-- on auth.users INSERT. The trigger creates a minimal row.
-- We ALTER it here to add all application-specific columns.
-- If deploying fresh, create the table explicitly:

CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    full_name TEXT,
    nisn TEXT,
    class_name TEXT,
    avatar_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    -- Added columns (from migrations):
    role TEXT DEFAULT 'student',
    status TEXT DEFAULT 'active',
    device_id TEXT,
    phone_number TEXT,

    -- Student detail columns:
    nipd TEXT,
    gender TEXT,
    birth_place TEXT,
    birth_date DATE,
    nik TEXT,
    religion TEXT,
    address TEXT,
    father_name TEXT,
    mother_name TEXT
);

-- Ensure columns exist (safe for existing deployments)
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'student';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS device_id TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS phone_number TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS nipd TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS gender TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS birth_place TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS birth_date DATE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS nik TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS religion TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS father_name TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS mother_name TEXT;

-- ────────────────────────────────────────────────────────────
-- 2. COMPANIES (DUDI)
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    address TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    radius INTEGER DEFAULT 100,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ────────────────────────────────────────────────────────────
-- 3. PLACEMENTS
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.placements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    start_date DATE,
    end_date DATE,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(student_id, company_id)
);

-- ────────────────────────────────────────────────────────────
-- 4. ATTENDANCE_LOGS
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.attendance_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    placement_id BIGINT REFERENCES public.placements(id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'Belum Hadir',
    check_in_time TIMESTAMPTZ,
    check_out_time TIMESTAMPTZ,
    check_in_photo TEXT,
    check_out_photo TEXT,
    check_in_latitude DOUBLE PRECISION,
    check_in_longitude DOUBLE PRECISION,
    check_out_latitude DOUBLE PRECISION,
    check_out_longitude DOUBLE PRECISION,
    date DATE,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Status constraint (comprehensive list used by the app)
ALTER TABLE attendance_logs
DROP CONSTRAINT IF EXISTS attendance_logs_status_check;

ALTER TABLE attendance_logs
ADD CONSTRAINT attendance_logs_status_check
CHECK (status IN ('Hadir', 'Izin', 'Sakit', 'Alpa', 'Terlambat', 'Diluar Jangkauan', 'Belum Hadir'));

-- ────────────────────────────────────────────────────────────
-- 5. DAILY_JOURNALS
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.daily_journals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    placement_id BIGINT REFERENCES public.placements(id) ON DELETE SET NULL,
    date DATE NOT NULL,
    activities TEXT NOT NULL,
    challenges TEXT,
    notes TEXT,
    evidence_url TEXT,
    is_approved BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ────────────────────────────────────────────────────────────
-- 6. SUPERVISOR_ASSIGNMENTS
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.supervisor_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(teacher_id, company_id)
);

-- ────────────────────────────────────────────────────────────
-- 7. ANNOUNCEMENTS
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.announcements (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    target_role TEXT DEFAULT 'all' CHECK (target_role IN ('student', 'teacher', 'all')),
    author_id UUID REFERENCES public.profiles(id) NOT NULL,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ────────────────────────────────────────────────────────────
-- 8. NOTIFICATIONS
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.notifications (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    type TEXT CHECK (type IN ('alert', 'info', 'success', 'warning')) DEFAULT 'info',
    is_read BOOLEAN DEFAULT false,
    action_link TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ────────────────────────────────────────────────────────────
-- 9. APP_CONFIG
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.app_config (
    key TEXT PRIMARY KEY,
    value TEXT,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ────────────────────────────────────────────────────────────
-- 10. AUDIT_LOGS
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    actor_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    action TEXT NOT NULL,
    table_name TEXT NOT NULL,
    record_id TEXT,
    details JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW()
);
