BEGIN;
UPDATE profiles SET class_name = 'XII TEI 3' WHERE full_name = 'CHANDRI REYKA AL PAJAR';
UPDATE profiles SET class_name = 'XII TEI 2' WHERE full_name = 'DAIS SITI AISMASRIPAH';
UPDATE profiles SET class_name = 'XII TEI 3' WHERE full_name = 'AGUNG PERMANA';
UPDATE profiles SET class_name = 'XII TEI 3' WHERE full_name = 'RAYNI NISYA SYAKINA';
UPDATE profiles SET class_name = 'XII TEI 3' WHERE full_name = 'TASYA NUR APIPAH';
UPDATE profiles SET class_name = 'XII TEI 3' WHERE full_name = 'ADRIAN';
UPDATE profiles SET class_name = 'XII TEI 2' WHERE full_name = 'AKBAR MAULANA ALI';
UPDATE profiles SET class_name = 'XII TEI 2' WHERE full_name = 'ALFIN SULTON NUR AULIYA';
UPDATE profiles SET class_name = 'XII TEI 2' WHERE full_name = 'FADILAH AKBAR';
UPDATE profiles SET class_name = 'XII TEI 2' WHERE full_name = 'RENDI RAHMAT GUMILAR';
UPDATE profiles SET class_name = 'XII TEI 3' WHERE full_name = 'BIMA ADITIA KUSDIANA';
UPDATE profiles SET class_name = 'XII TEI 3' WHERE full_name = 'DAPA NUGRAHA';
UPDATE profiles SET class_name = 'XII TEI 3' WHERE full_name = 'DENIS';
UPDATE profiles SET class_name = 'XII TEI 3' WHERE full_name = 'IKBAL PAMBUDI OSRIBILLAH';
UPDATE profiles SET class_name = 'XII TEI 2' WHERE full_name = 'AURA NURANI MALIKA';
UPDATE profiles SET class_name = 'XII TEI 3' WHERE full_name = 'REVALINA MIFTAHUL FAUZIYYAH';
UPDATE profiles SET class_name = 'XII TEI 2' WHERE full_name = 'DINDIN MUHAMMAD NURDIN PAMUNGKAS';
UPDATE profiles SET class_name = 'XII TEI 2' WHERE full_name = 'SAIF RIZAL';
UPDATE profiles SET class_name = 'XII TEI 1' WHERE full_name = 'KASMARA NURIL AGNIA';
UPDATE profiles SET class_name = 'XII TEI 1' WHERE full_name = 'TALITA PUTRI NURAINI';
UPDATE profiles SET class_name = 'XII TEI 2' WHERE full_name = 'AHMAD FAHMI MUSTOFA';
UPDATE profiles SET class_name = 'XII TEI 2' WHERE full_name = 'RAFI PASHA';
UPDATE profiles SET class_name = 'XII TEI 3' WHERE full_name = 'RANISA AGUSTINA';
UPDATE profiles SET class_name = 'XII TEI 3' WHERE full_name = 'SISKA SETIANI';
UPDATE profiles SET class_name = 'XII TEI 3' WHERE full_name = 'MUHAMAD BAGAS ADITIA PUTRA';
UPDATE profiles SET class_name = 'XII TEI 1' WHERE full_name = 'ARDIAN AKBAR FADILAH';
UPDATE profiles SET class_name = 'XII TEI 1' WHERE full_name = 'AHMAD FAISAL';
UPDATE profiles SET class_name = 'XII TEI 1' WHERE full_name = 'IKHSAN NAUVAL F';
UPDATE profiles SET class_name = 'XII TEI 1' WHERE full_name = 'FAHRI RIZKI MAULANA';
UPDATE profiles SET class_name = 'XII TEI 2' WHERE full_name = 'AGNIA SEPTIA PEBRIANI';
UPDATE profiles SET class_name = 'XII TEI 2' WHERE full_name = 'DONNY PUTRA ISYANTO';
UPDATE profiles SET class_name = 'XII TEI 2' WHERE full_name = 'LUKI';
UPDATE profiles SET class_name = 'XII TEI 3' WHERE full_name = 'M RIFA''I HADIAN';
UPDATE profiles SET class_name = 'XII TEI 3' WHERE full_name = 'MUHAMAD RIJAL';
UPDATE profiles SET class_name = 'XII TEI 1' WHERE full_name = 'SRI ASIPA';
UPDATE profiles SET class_name = 'XII TEI 1' WHERE full_name = 'SYINDI KARTIKA';
UPDATE profiles SET class_name = 'XII TEI 2' WHERE full_name = 'ALDO DINI YUDISTRIRA';
UPDATE profiles SET class_name = 'XII TEI 2' WHERE full_name = 'DIAN ARDIANSYAH';
UPDATE profiles SET class_name = 'XII TEI 2' WHERE full_name = 'REYSA RAHMA AULIA';
UPDATE profiles SET class_name = 'XII TEI 2' WHERE full_name = 'AGNI NURUL FAUZIAH';
UPDATE profiles SET class_name = 'XII TEI 2' WHERE full_name = 'AHMAD WAHDAN PAQIH';
UPDATE profiles SET class_name = 'XII TEI 2' WHERE full_name = 'REYHAN SAPAWI';
UPDATE profiles SET class_name = 'XII TEI 3' WHERE full_name = 'FAZRIEL M NURAGUNG';
UPDATE profiles SET class_name = 'XII TEI 1' WHERE full_name = 'AHMAD NURDIN';
UPDATE profiles SET class_name = 'XII TEI 1' WHERE full_name = 'MUHAMAD RIAN';
UPDATE profiles SET class_name = 'XII TEI 1' WHERE full_name = 'ERPAN SETIAWAN';
UPDATE profiles SET class_name = 'XII TEI 1' WHERE full_name = 'M. FAREL ARIFIN';
UPDATE profiles SET class_name = 'XII TEI 2' WHERE full_name = 'AKMAL FAIRUS';
UPDATE profiles SET class_name = 'XII TEI 2' WHERE full_name = 'SAHID UMAR MUSTOFA';
UPDATE profiles SET class_name = 'XII TEI 2' WHERE full_name = 'GAGAN RENALDI';
UPDATE profiles SET class_name = 'XII TEI 2' WHERE full_name = 'KIKI NAWAWI';
UPDATE profiles SET class_name = 'XII TEI 3' WHERE full_name = 'CHELSY NURHAYATI';
UPDATE profiles SET class_name = 'XII TEI 3' WHERE full_name = 'ENENG NURAJIJAH';
UPDATE profiles SET class_name = 'XII TEI 3' WHERE full_name = 'LIDYA MARTA';
UPDATE profiles SET class_name = 'XII TEI 3' WHERE full_name = 'RAHMA';
UPDATE profiles SET class_name = 'XII TEI 3' WHERE full_name = 'NADIA ABRILIA SOLIHAT';
UPDATE profiles SET class_name = 'XII TEI 1' WHERE full_name = 'MOHAMMAD AKBAR FADJRILLAH';
UPDATE profiles SET class_name = 'XII TEI 1' WHERE full_name = 'AMBAR MUSTOFA';
UPDATE profiles SET class_name = 'XII TEI 1' WHERE full_name = 'BAYU ISLAMI PASA';
UPDATE profiles SET class_name = 'XII TEI 1' WHERE full_name = 'LUTFI MUHAMMAD LINTANG';
UPDATE profiles SET class_name = 'XII TEI 1' WHERE full_name = 'MOCH BAGJA SAPUTRA';
UPDATE profiles SET class_name = 'XII TEI 1' WHERE full_name = 'MOCH. FADIL AL-RIZKY';
UPDATE profiles SET class_name = 'XII TEI 2' WHERE full_name = 'AGUNG BIJAKSANA';
UPDATE profiles SET class_name = 'XII TEI 2' WHERE full_name = 'AHMAD DENA';
UPDATE profiles SET class_name = 'XII TEI 2' WHERE full_name = 'AMANDA NURFADILAH SYAPUTRI';
UPDATE profiles SET class_name = 'XII TEI 2' WHERE full_name = 'ANDRAY';
UPDATE profiles SET class_name = 'XII TEI 2' WHERE full_name = 'SYAKILA AZZAHRA NURARAFAH';
UPDATE profiles SET class_name = 'XII TEI 3' WHERE full_name = 'MUHAMAD FAHRI';
UPDATE profiles SET class_name = 'XII TEI 3' WHERE full_name = 'MUHAMMAD FACHRY RADITHA PRATAMA';
UPDATE profiles SET class_name = 'XII TEI 3' WHERE full_name = 'MUHAMMAD YUSUP';
UPDATE profiles SET class_name = 'XII TEI 1' WHERE full_name = 'LINDA HENING CAHAYAWATI';
UPDATE profiles SET class_name = 'XII TEI 1' WHERE full_name = 'BINTANG PRATAMA';
UPDATE profiles SET class_name = 'XII TEI 1' WHERE full_name = 'M IKBAL RAMDHANI';
UPDATE profiles SET class_name = 'XII TEI 1' WHERE full_name = 'MUHAMAD RIFKI ARDIANSYAH';
UPDATE profiles SET class_name = 'XII TEI 1' WHERE full_name = 'RAMA RAMADAN';
UPDATE profiles SET class_name = 'XII TEI 1' WHERE full_name = 'YOGA APRIAN SAEPULOH';
UPDATE profiles SET class_name = 'XII TEI 2' WHERE full_name = 'ASEP FIRMAN AL KAHFI';
UPDATE profiles SET class_name = 'XII TEI 2' WHERE full_name = 'YOGI MAULANA';
UPDATE profiles SET class_name = 'XII TEI 3' WHERE full_name = 'ANGGA PERMANA';
UPDATE profiles SET class_name = 'XII TEI 3' WHERE full_name = 'EGI PADILAH';
UPDATE profiles SET class_name = 'XII TEI 3' WHERE full_name = 'MUHAMAD AKBAR SAPUTRA';
UPDATE profiles SET class_name = 'XII TEI 3' WHERE full_name = 'MUHAMMAD SHIDIK';
UPDATE profiles SET class_name = 'XII TEI 3' WHERE full_name = 'MUHAMAD YESAL ALFAHRI';
UPDATE profiles SET class_name = 'XII TEI 2' WHERE full_name = 'ALDI WIJAYA';
UPDATE profiles SET class_name = 'XII TEI 2' WHERE full_name = 'MUHAMAD AKBAR';
UPDATE profiles SET class_name = 'XII TEI 2' WHERE full_name = 'BAYU MARDIANSYAH';
UPDATE profiles SET class_name = 'XII TEI 2' WHERE full_name = 'SUKMAWATI';
UPDATE profiles SET class_name = 'XII TEI 1' WHERE full_name = 'ARYA MUHAMAD PAISAL';
UPDATE profiles SET class_name = 'XII TEI 1' WHERE full_name = 'DADAN SURAHMAN';
UPDATE profiles SET class_name = 'XII TEI 1' WHERE full_name = 'MUHAMMAD NURFARIZ';
UPDATE profiles SET class_name = 'XII TEI 1' WHERE full_name = 'WAFI ALFARIZI';
UPDATE profiles SET class_name = 'XII TEI 3' WHERE full_name = 'MOHAMAD ALIP BURHAN HIDAYAT';
UPDATE profiles SET class_name = 'XII TEI 3' WHERE full_name = 'MUHAMAD MI''RAJ';
UPDATE profiles SET class_name = 'XII TEI 3' WHERE full_name = 'MUHAMMAD YUSUP';
UPDATE profiles SET class_name = 'XII TEI 3' WHERE full_name = 'RAFLI JULIANSYAH';
UPDATE profiles SET class_name = 'XII TEI 3' WHERE full_name = 'SATRIA ERLANGGA PUTRA';
UPDATE profiles SET class_name = 'XII TEI 1' WHERE full_name = 'SELI RAHMA SARI';
UPDATE profiles SET class_name = 'XII TEI 1' WHERE full_name = 'SITI WARDAH FAUZIAH';
UPDATE profiles SET class_name = 'XII TEI 1' WHERE full_name = 'SINTIA AGUSTIN';
UPDATE profiles SET class_name = 'XII TEI 1' WHERE full_name = 'ANISA NURAENI';
UPDATE profiles SET class_name = 'XII TEI 2' WHERE full_name = 'RINA KUSUMAH';
UPDATE profiles SET class_name = 'XII TEI 1' WHERE full_name = 'NENG TIARA';
UPDATE profiles SET class_name = 'XII TEI 1' WHERE full_name = 'RIA SETIA';
UPDATE profiles SET class_name = 'XII TEI 3' WHERE full_name = 'NAILA ANGGITA JAHRA';
UPDATE profiles SET class_name = 'XII TEI 3' WHERE full_name = 'AMELIA HERDIYANI';
UPDATE profiles SET class_name = 'XII TEI 3' WHERE full_name = 'MUHAMAD GALANG RAMADHAN';
UPDATE profiles SET class_name = 'XII TEI 2' WHERE full_name = 'VIANI SRI MALIK';
COMMIT;
