-- 1. Add Role Column
ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'student';

-- 2. Create Supervisor Assignments
CREATE TABLE IF NOT EXISTS supervisor_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  company_id BIGINT REFERENCES companies(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(teacher_id, company_id)
);

-- 3. RLS
ALTER TABLE supervisor_assignments ENABLE ROW LEVEL SECURITY;

-- Drop existing policy if exists to avoid error on rerun
DROP POLICY IF EXISTS "Teachers can view own assignments" ON supervisor_assignments;

CREATE POLICY "Teachers can view own assignments" 
ON supervisor_assignments FOR SELECT 
USING (auth.uid() = teacher_id);

-- 4. Seed Data (For Development)
UPDATE profiles 
SET role = 'teacher' 
WHERE id = '49778431-1c8a-4383-9973-b2bc7c8c44c8';

INSERT INTO supervisor_assignments (teacher_id, company_id)
VALUES ('49778431-1c8a-4383-9973-b2bc7c8c44c8', 10)
ON CONFLICT (teacher_id, company_id) DO NOTHING;
